In [1]:
# Create 3X3 game board, 0 = empty, 1 = player 1, 2 = player 2
# input position for
    # range 0 - 2 integer
    # empoty position
# show game board 
# check if anyone win
    # check horizontal
    # check vertical
    # check diagonal
# if win  => show won player
# if not win 
    # if all filled => draw
    # if not => input postition for another player

In [2]:
import numpy as np

In [3]:
board = np.zeros((3,3))
board

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
sum(board[:,2] == 0)

3

In [7]:
if (0,0) in [(0,0)]:
    print("yes")

yes


In [8]:
diagonal_right = [(i, -i-1) for i in range(3)]

In [9]:
diagonal_right

[(0, -1), (1, -2), (2, -3)]

In [10]:
def game_update(game_board, player, lower, upper):
    row_input = "X"
    col_input = "X"
    while not row_input.isdigit() or not col_input.isdigit() or int(row_input) > upper or int(row_input) < lower or int(col_input) > upper or int(col_input) < lower or game_board[int(row_input),int(col_input)] != 0:
        user_input = input('Player{}, Please enter your row,col position, e.g.0,0):'.format(str(player)))
        input_list = user_input.split(",")
        row_input = input_list[0]
        col_input = input_list[1]
    row_input = int(row_input)
    col_input = int(col_input)
    game_board[row_input,col_input] = player
    return game_board, (row_input, col_input)

In [11]:
def win_check(game_board, player, update_step, board_size):
    #check horizontal
    if len(set(game_board[update_step[0],])) == 1 and list(set(game_board[update_step[0],]))[0] == player:
        return player
    #Check vertical
    elif len(set(game_board[:,update_step[1]])) == 1 and list(set(game_board[:,update_step[1]]))[0] == player:
        return player
    #cross check: left to right
    elif len(set([game_board[i,i] for i in range(board_size)])) == 1 and list(set([game_board[i,i] for i in range(board_size)]))[0] == player:
        return player
    #cross check: right to left
    elif len(set([game_board[i,-i-1] for i in range(board_size)])) == 1 and list(set([game_board[i,-i-1] for i in range(board_size)]))[0] == player:
        return player
    else:
        return 0

In [12]:
len([])

0

In [13]:
# initial State
def tic_tac_toe(board_size):
    player_1 = 1
    player_2 = 2
    game_board = np.zeros((board_size, board_size))
    max_step = board_size
    lower = 0
    upper = board_size -1
    step = 0
    print(game_board)
    continue_play = True
    while continue_play:
        for player in [1,2]:
            game_board, update_step = game_update(game_board, player, lower, upper)
            print(game_board)
            game_status = win_check(game_board, player, update_step, board_size) #win lose draw?
            step += 1
            if game_status != 0:
                print("Game ended, player{} wins!".format(str(game_status)))
                continue_play = False
                break
            if step == 9:
                print("Draw game")
                continue_play = False
                break
            

In [15]:
tic_tac_toe(3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Player1, Please enter your row,col position, e.g.0,0):1,2
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Player2, Please enter your row,col position, e.g.0,0):2,1
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 2. 0.]]
Player1, Please enter your row,col position, e.g.0,0):1,1
[[0. 0. 0.]
 [0. 1. 1.]
 [0. 2. 0.]]
Player2, Please enter your row,col position, e.g.0,0):1,0
[[0. 0. 0.]
 [2. 1. 1.]
 [0. 2. 0.]]
Player1, Please enter your row,col position, e.g.0,0):3,1
Player1, Please enter your row,col position, e.g.0,0):2,1
Player1, Please enter your row,col position, e.g.0,0):2,2
[[0. 0. 0.]
 [2. 1. 1.]
 [0. 2. 1.]]
Player2, Please enter your row,col position, e.g.0,0):0,0
[[2. 0. 0.]
 [2. 1. 1.]
 [0. 2. 1.]]
Player1, Please enter your row,col position, e.g.0,0):0,2
[[2. 0. 1.]
 [2. 1. 1.]
 [0. 2. 1.]]
Game ended, player1 wins!


## np.zeros((3,3)).shape